# Generated by Django 4.0.2 on 2022-06-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BooksItem',
        ),
        migrations.DeleteModel(
            name='ClothesItem',
        ),
    ]
